<%@ page language="java" contentType="text/html; charset=UTF-8" isELIgnored="false"%>
<%@ taglib prefix="s" uri="/struts-tags"%>
<html>
	<head>
		<title>批量导入配置</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link href="../../css/style.css" rel="stylesheet" type="text/css">

</head>

<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" style="overflow:hidden;">
<table cellspacing=0 cellpadding=0 border=0 width="100%">
  <tr>
   <td width="2%" height="22" align="center" background="../../images/main20100521_582.gif" style="color:#FFFFFF; font-weight:bold;"><img src="../../images/modpass.gif" width="16" height="16"></td>
   <td width="98%" background="../../images/main20100521_582.gif" style="color:#FFFFFF; font-weight:bold;">文档库管理:</td>
  </tr>
</table>
<div style="position: absolute; overflow-x: hidden; overflow-y: scroll; height:95%; width: 100%; padding-top: 5px;">
  <table width="98%" border="0" align="center" cellpadding=3 cellspacing=0>
    <tr>
      <td align=right style="padding-right: 1px" height="32"><span class="mmBtn" style="cursor:hand;"><a onClick="location.href='classificationlist.jsp'">&nbsp;按配置分类查看&nbsp;</a></span>&nbsp; <span class="mmBtn" style="cursor:hand;"><a onClick="location.href='locationlist.jsp'">&nbsp;按地理位置查看&nbsp;</a></span>&nbsp; <span class="mmBtn" style="cursor:hand;"><a onClick="location.href='departmentlist.jsp'">&nbsp;按部门查看&nbsp;</a></span>&nbsp; <span class="mmBtn" style="cursor:hand;"><a onClick="location.href='statuslist.jsp'">&nbsp;按使用状态查看&nbsp;</a></span></td>
    </tr>
  </table>
  <table width="98%" border="0" align="center" cellpadding="0" cellspacing="0">
    <tr>
      <td width="99%"><img src="../../images/main20100521dot04.gif">&nbsp;<b>配置文档分类查询管理:</b>&nbsp;</td>
    </tr>
  </table>
  <table width="98%" border="0" align="center" cellpadding="2" cellspacing="1" bgcolor="#b5d6e6">
	<tr>
	  <td height="22" colspan="2" background="../../images/main20100521_58.gif" class="alllisttitle">文档目录</td>
    </tr>
	<tr> 
	  <td width="40%" valign="top" bgcolor="#FFFFFF"><table width="100%" border="0" cellspacing="0" cellpadding="0" height="100%">
        <tr>
          <td width="100%" align="left" valign="top"><table width="100%" border="0" align="center" cellpadding="4" cellspacing="1" bgcolor="#b5d6e6">
  <tr>
    <td height="280" valign="top" bgcolor="#FFFFFF"><div style="position: absolute; overflow-x: hidden; overflow-y: scroll; height:270; width: 100%; padding-top: 5px; left: 22px;">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td style="line-height: 19px; font-family: Tahoma" bgColor="white" nowrap><div><img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('230230').style.display=='none'){document.getElementById('230230').style.display='';this.src='../../img/jian.jpg'}else{document.getElementById('230230').style.display='none';this.src='../../img/jia.jpg'}">&nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a href="hardwarenewlist.jsp" target="file">项目文档</a></font></font>
            <div id="230230" style="padding-left: 20px; display: none"> <img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('239239').style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('239239').style.display=''}else{document.getElementById('239239').style.display='none';this.src='../../img/jia.jpg'}">
                
              &nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="239o" name="|230,|239,o">软件项目文档</a></font></font><br>
              <div id="239239" style="padding-left: 20px; display: none"> <img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('243243').style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('243243').style.display=''}else{document.getElementById('243243').style.display='none';this.src='../../img/jia.jpg'}">
                &nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="243o" name="|230,|239,|243,o">品牌服务器</a></font></font><br>
                <div id="243243" style="padding-left: 20px; display: none"></div>
                <img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('244244').style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('244244').style.display=''}else{document.getElementById('244244').style.display='none';this.src='../../img/jia.jpg'}">
                &nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="244o" name="|230,|239,|244,o">普PC服务器</a></font></font><br>
                <div id="244244" style="padding-left: 20px; display: none"></div>
              </div>
              <img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('240240').style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('240240').style.display=''}else{document.getElementById('240240').style.display='none';this.src='../../img/jia.jpg'}">
              &nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="240o" name="|230,|240,o">桌面机</a></font></font><br>
              <div id="240240" style="padding-left: 20px; display: none"> <img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('245245').style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('245245').style.display=''}else{document.getElementById('245245').style.display='none';this.src='../../img/jia.jpg'}">
                &nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="245o" name="|230,|240,|245,o">台式机</a></font></font><br>
                <div id="245245" style="padding-left: 20px; display: none"></div>
                <img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('246246').style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('246246').style.display=''}else{document.getElementById('246246').style.display='none';this.src='../../img/jia.jpg'}">
                &nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="246o" name="|230,|240,|246,o">笔记本</a></font></font><br>
                <div id="246246" style="padding-left: 20px; display: none"></div>
              </div>
              <img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('241241').style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('241241').style.display=''}else{document.getElementById('241241').style.display='none';this.src='../../img/jia.jpg'}">
              &nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="241o" name="|230,|241,o">网络设备</a></font></font><br>
              <div id="241241" style="padding-left: 20px; display: none"> <img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('247247').style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('247247').style.display=''}else{document.getElementById('247247').style.display='none';this.src='../../img/jia.jpg'}">
                &nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="247o" name="|230,|241,|247,o">路由器</a></font></font><br>
                <div id="247247" style="padding-left: 20px; display: none"></div>
                <img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('248248').style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('248248').style.display=''}else{document.getElementById('248248').style.display='none';this.src='../../img/jia.jpg'}">
                &nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="248o" name="|230,|241,|248,o">交换机</a></font></font><br>
                <div id="248248" style="padding-left: 20px; display: none"></div>
                <img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('249249').style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('249249').style.display=''}else{document.getElementById('249249').style.display='none';this.src='../../img/jia.jpg'}">
                &nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="249o" name="|230,|241,|249,o">防火墙</a></font></font><br>
                <div id="249249" style="padding-left: 20px; display: none"></div>
                <img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('250250').style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('250250').style.display=''}else{document.getElementById('250250').style.display='none';this.src='../../img/jia.jpg'}">
                &nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="250o" name="|230,|241,|250,o">其它类</a></font></font><br>
                <div id="250250" style="padding-left: 20px; display: none"></div>
              </div>
              <img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('242242').style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('242242').style.display=''}else{document.getElementById('242242').style.display='none';this.src='../../img/jia.jpg'}">
              &nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="242o" name="|230,|242,o">外围设备</a></font></font><br>
              <div id="242242" style="padding-left: 20px; display: none"> <img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('251251').style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('251251').style.display=''}else{document.getElementById('251251').style.display='none';this.src='../../img/jia.jpg'}">
                &nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="251o" name="|230,|242,|251,o">打印机</a></font></font><br>
                <div id="251251" style="padding-left: 20px; display: none"></div>
                <img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('252252').style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('252252').style.display=''}else{document.getElementById('252252').style.display='none';this.src='../../img/jia.jpg'}">
                &nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="252o" name="|230,|242,|252,o">扫描仪</a></font></font><br>
                <div id="252252" style="padding-left: 20px; display: none"></div>
                <img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('253253').style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('253253').style.display=''}else{document.getElementById('253253').style.display='none';this.src='../../img/jia.jpg'}">
                &nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="253o" name="|230,|242,|253,o">复印机</a></font></font><br>
                <div id="253253" style="padding-left: 20px; display: none"></div>
                <img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('254254').style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('254254').style.display=''}else{document.getElementById('254254').style.display='none';this.src='../../img/jia.jpg'}">
                &nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="254o" name="|230,|242,|254,o">显示器</a></font></font><br>
                <div id="254254" style="padding-left: 20px; display: none"></div>
                <img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('255255').style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('255255').style.display=''}else{document.getElementById('255255').style.display='none';this.src='../../img/jia.jpg'}">
                &nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="255o" name="|230,|242,|255,o">一体机</a></font></font><br>
                <div id="255255" style="padding-left: 20px; display: none"></div>
              </div>
            </div>
          </div>
            </td>
        </tr>
      </table>
    </div></td>
  </tr>
</table>
            <table width="100%" border="0" cellspacing="0" cellpadding="4">
              <tr>
                <td width="1%" nowrap="nowrap" style="padding-right: 0px"><img src="../../img/check.jpg" width="18" height="18" align="absmiddle" /></td>
                <td width="1%" style="padding-left: 1px"><select name="Type">
                    <option value="Title">标题</option>
                    <option value="Content">关键词</option>
                    <option value="ITer">作者</option>
                    <option value="NoPro">项目文档</option>
                  </select>
                </td>
                <td width="99%"><input name="Key" type="text" id="Key" style="width: 100%" /></td>
                <td width="1%"><input type="button" value="搜索" onClick="window.solution.location='../prob/?NowAction=documentlist&amp;Type='+document.getElementById('Type').value+'&amp;Key='+document.getElementById('Key').value" class="mmBtn_sm" name="button" /></td>
              </tr>
            </table></td>
        </tr>
        <tr>
          <td height="10" background="../img/tr.gif">&nbsp;</td>
        </tr>
      </table></td>
	  <td width="60%" height="240" align="center" valign="top" bgcolor="#FFFFFF" style="padding-top:6px;"><iframe width="100%" height="270" scrolling="auto" frameborder="0" name="file"></iframe></td>
	</tr>
</table>
<table width="98%" border="0" align="center" cellpadding="0" cellspacing="0" style="display:none;" id="TB">
    <tr>
      <td height=22 colspan="6" align="right" valign="top" style="padding-right:300px;"><div id="Cate" style="position:absolute; overflow-y: scroll; width: 300px; height:150px; z-index:1; border: 1px solid #cccccc;"><table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td style="line-height: 19px; font-family: Tahoma" bgColor="white" nowrap>
	
			<div><img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.all.TB.style.display=='none'){document.getElementById('230230').style.display='';this.src='../../img/jian.jpg'}else{document.getElementById('230230').style.display='none';this.src='../../img/jia.jpg'}"><input type="radio" value="|230," onClick="window.parent.document.getElementById('ZiCLB_2').value='硬件';window.parent.document.getElementById('ZiCLB').value='|230,';window.parent.document.getElementById('Cate').style.visibility='hidden';window.parent.document.getElementById('Postit').submit()" style="border: 0px; border-top: 6px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept">&nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="230o" name="|230,o">硬件</a></font></font><div id="230230" style="padding-left: 20px; display: none">
			<img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.all.TB.style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('239239').style.display=''}else{document.getElementById('239239').style.display='none';this.src='../../img/jia.jpg'}"><input type="radio" value="|230,|239," onClick="window.parent.document.getElementById('ZiCLB_2').value='服务器';window.parent.document.getElementById('ZiCLB').value='|230,|239,';window.parent.document.getElementById('Cate').style.visibility='hidden';window.parent.document.getElementById('Postit').submit()" style="border: 0px; border-top: 6px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept">&nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="239o" name="|230,|239,o">服务器</a></font></font><br><div id="239239" style="padding-left: 20px; display: none">
			<img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.all.TB.style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('243243').style.display=''}else{document.getElementById('243243').style.display='none';this.src='../../img/jia.jpg'}"><input type="radio" value="|230,|239,|243," onClick="window.parent.document.getElementById('ZiCLB_2').value='品牌服务器';window.parent.document.getElementById('ZiCLB').value='|230,|239,|243,';window.parent.document.getElementById('Cate').style.visibility='hidden';window.parent.document.getElementById('Postit').submit()" style="border: 0px; border-top: 6px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept">&nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="243o" name="|230,|239,|243,o">品牌服务器</a></font></font><br><div id="243243" style="padding-left: 20px; display: none"></div>
			
			<img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.all.TB.style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('244244').style.display=''}else{document.getElementById('244244').style.display='none';this.src='../../img/jia.jpg'}"><input type="radio" value="|230,|239,|244," onClick="window.parent.document.getElementById('ZiCLB_2').value='普PC服务器';window.parent.document.getElementById('ZiCLB').value='|230,|239,|244,';window.parent.document.getElementById('Cate').style.visibility='hidden';window.parent.document.getElementById('Postit').submit()" style="border: 0px; border-top: 6px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept">&nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="244o" name="|230,|239,|244,o">普PC服务器</a></font></font><br><div id="244244" style="padding-left: 20px; display: none"></div>
			</div>
			
			<img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('240240').style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('240240').style.display=''}else{document.getElementById('240240').style.display='none';this.src='../../img/jia.jpg'}"><input type="radio" value="|230,|240," onClick="window.parent.document.getElementById('ZiCLB_2').value='桌面机';window.parent.document.getElementById('ZiCLB').value='|230,|240,';window.parent.document.getElementById('Cate').style.visibility='hidden';window.parent.document.getElementById('Postit').submit()" style="border: 0px; border-top: 6px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept">&nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="240o" name="|230,|240,o">桌面机</a></font></font><br><div id="240240" style="padding-left: 20px; display: none">
			<img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('245245').style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('245245').style.display=''}else{document.getElementById('245245').style.display='none';this.src='../../img/jia.jpg'}"><input type="radio" value="|230,|240,|245," onClick="window.parent.document.getElementById('ZiCLB_2').value='台式机';window.parent.document.getElementById('ZiCLB').value='|230,|240,|245,';window.parent.document.getElementById('Cate').style.visibility='hidden';window.parent.document.getElementById('Postit').submit()" style="border: 0px; border-top: 6px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept">&nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="245o" name="|230,|240,|245,o">台式机</a></font></font><br><div id="245245" style="padding-left: 20px; display: none"></div>
			
			<img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('246246').style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('246246').style.display=''}else{document.getElementById('246246').style.display='none';this.src='../../img/jia.jpg'}"><input type="radio" value="|230,|240,|246," onClick="window.parent.document.getElementById('ZiCLB_2').value='笔记本';window.parent.document.getElementById('ZiCLB').value='|230,|240,|246,';window.parent.document.getElementById('Cate').style.visibility='hidden';window.parent.document.getElementById('Postit').submit()" style="border: 0px; border-top: 6px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept">&nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="246o" name="|230,|240,|246,o">笔记本</a></font></font><br><div id="246246" style="padding-left: 20px; display: none"></div>
			</div>
			
			<img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('241241').style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('241241').style.display=''}else{document.getElementById('241241').style.display='none';this.src='../../img/jia.jpg'}"><input type="radio" value="|230,|241," onClick="window.parent.document.getElementById('ZiCLB_2').value='网络设备';window.parent.document.getElementById('ZiCLB').value='|230,|241,';window.parent.document.getElementById('Cate').style.visibility='hidden';window.parent.document.getElementById('Postit').submit()" style="border: 0px; border-top: 6px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept">&nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="241o" name="|230,|241,o">网络设备</a></font></font><br><div id="241241" style="padding-left: 20px; display: none">
			<img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('247247').style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('247247').style.display=''}else{document.getElementById('247247').style.display='none';this.src='../../img/jia.jpg'}"><input type="radio" value="|230,|241,|247," onClick="window.parent.document.getElementById('ZiCLB_2').value='路由器';window.parent.document.getElementById('ZiCLB').value='|230,|241,|247,';window.parent.document.getElementById('Cate').style.visibility='hidden';window.parent.document.getElementById('Postit').submit()" style="border: 0px; border-top: 6px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept">&nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="247o" name="|230,|241,|247,o">路由器</a></font></font><br><div id="247247" style="padding-left: 20px; display: none"></div>
			
			<img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('248248').style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('248248').style.display=''}else{document.getElementById('248248').style.display='none';this.src='../../img/jia.jpg'}"><input type="radio" value="|230,|241,|248," onClick="window.parent.document.getElementById('ZiCLB_2').value='交换机';window.parent.document.getElementById('ZiCLB').value='|230,|241,|248,';window.parent.document.getElementById('Cate').style.visibility='hidden';window.parent.document.getElementById('Postit').submit()" style="border: 0px; border-top: 6px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept">&nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="248o" name="|230,|241,|248,o">交换机</a></font></font><br><div id="248248" style="padding-left: 20px; display: none"></div>
			
			<img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('249249').style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('249249').style.display=''}else{document.getElementById('249249').style.display='none';this.src='../../img/jia.jpg'}"><input type="radio" value="|230,|241,|249," onClick="window.parent.document.getElementById('ZiCLB_2').value='防火墙';window.parent.document.getElementById('ZiCLB').value='|230,|241,|249,';window.parent.document.getElementById('Cate').style.visibility='hidden';window.parent.document.getElementById('Postit').submit()" style="border: 0px; border-top: 6px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept">&nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="249o" name="|230,|241,|249,o">防火墙</a></font></font><br><div id="249249" style="padding-left: 20px; display: none"></div>
			
			<img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('250250').style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('250250').style.display=''}else{document.getElementById('250250').style.display='none';this.src='../../img/jia.jpg'}"><input type="radio" value="|230,|241,|250," onClick="window.parent.document.getElementById('ZiCLB_2').value='其它类';window.parent.document.getElementById('ZiCLB').value='|230,|241,|250,';window.parent.document.getElementById('Cate').style.visibility='hidden';window.parent.document.getElementById('Postit').submit()" style="border: 0px; border-top: 6px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept">&nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="250o" name="|230,|241,|250,o">其它类</a></font></font><br><div id="250250" style="padding-left: 20px; display: none"></div>
			</div>
			
			<img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('242242').style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('242242').style.display=''}else{document.getElementById('242242').style.display='none';this.src='../../img/jia.jpg'}"><input type="radio" value="|230,|242," onClick="window.parent.document.getElementById('ZiCLB_2').value='外围设备';window.parent.document.getElementById('ZiCLB').value='|230,|242,';window.parent.document.getElementById('Cate').style.visibility='hidden';window.parent.document.getElementById('Postit').submit()" style="border: 0px; border-top: 6px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept">&nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="242o" name="|230,|242,o">外围设备</a></font></font><br><div id="242242" style="padding-left: 20px; display: none">
			<img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('251251').style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('251251').style.display=''}else{document.getElementById('251251').style.display='none';this.src='../../img/jia.jpg'}"><input type="radio" value="|230,|242,|251," onClick="window.parent.document.getElementById('ZiCLB_2').value='打印机';window.parent.document.getElementById('ZiCLB').value='|230,|242,|251,';window.parent.document.getElementById('Cate').style.visibility='hidden';window.parent.document.getElementById('Postit').submit()" style="border: 0px; border-top: 6px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept">&nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="251o" name="|230,|242,|251,o">打印机</a></font></font><br><div id="251251" style="padding-left: 20px; display: none"></div>
			
			<img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('252252').style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('252252').style.display=''}else{document.getElementById('252252').style.display='none';this.src='../../img/jia.jpg'}"><input type="radio" value="|230,|242,|252," onClick="window.parent.document.getElementById('ZiCLB_2').value='扫描仪';window.parent.document.getElementById('ZiCLB').value='|230,|242,|252,';window.parent.document.getElementById('Cate').style.visibility='hidden';window.parent.document.getElementById('Postit').submit()" style="border: 0px; border-top: 6px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept">&nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="252o" name="|230,|242,|252,o">扫描仪</a></font></font><br><div id="252252" style="padding-left: 20px; display: none"></div>
			
			<img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('253253').style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('253253').style.display=''}else{document.getElementById('253253').style.display='none';this.src='../../img/jia.jpg'}"><input type="radio" value="|230,|242,|253," onClick="window.parent.document.getElementById('ZiCLB_2').value='复印机';window.parent.document.getElementById('ZiCLB').value='|230,|242,|253,';window.parent.document.getElementById('Cate').style.visibility='hidden';window.parent.document.getElementById('Postit').submit()" style="border: 0px; border-top: 6px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept">&nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="253o" name="|230,|242,|253,o">复印机</a></font></font><br><div id="253253" style="padding-left: 20px; display: none"></div>
			
			<img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('254254').style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('254254').style.display=''}else{document.getElementById('254254').style.display='none';this.src='../../img/jia.jpg'}"><input type="radio" value="|230,|242,|254," onClick="window.parent.document.getElementById('ZiCLB_2').value='显示器';window.parent.document.getElementById('ZiCLB').value='|230,|242,|254,';window.parent.document.getElementById('Cate').style.visibility='hidden';window.parent.document.getElementById('Postit').submit()" style="border: 0px; border-top: 6px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept">&nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="254o" name="|230,|242,|254,o">显示器</a></font></font><br><div id="254254" style="padding-left: 20px; display: none"></div>
			
			<img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('255255').style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('255255').style.display=''}else{document.getElementById('255255').style.display='none';this.src='../../img/jia.jpg'}"><input type="radio" value="|230,|242,|255," onClick="window.parent.document.getElementById('ZiCLB_2').value='一体机';window.parent.document.getElementById('ZiCLB').value='|230,|242,|255,';window.parent.document.getElementById('Cate').style.visibility='hidden';window.parent.document.getElementById('Postit').submit()" style="border: 0px; border-top: 6px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept">&nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="255o" name="|230,|242,|255,o">一体机</a></font></font><br><div id="255255" style="padding-left: 20px; display: none"></div>
			</div>
			</div></div>
		
			<div><img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('231231').style.display=='none'){document.getElementById('231231').style.display='';this.src='../../img/jian.jpg'}else{document.getElementById('231231').style.display='none';this.src='../../img/jia.jpg'}"><input type="radio" value="|231," onClick="window.parent.document.getElementById('ZiCLB_2').value='软件';window.parent.document.getElementById('ZiCLB').value='|231,';window.parent.document.getElementById('Cate').style.visibility='hidden';window.parent.document.getElementById('Postit').submit()" style="border: 0px; border-top: 6px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept">&nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="231o" name="|231,o">软件</a></font></font><div id="231231" style="padding-left: 20px; display: none"></div></div>
		
			<div><img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('256256').style.display=='none'){document.getElementById('256256').style.display='';this.src='../../img/jian.jpg'}else{document.getElementById('256256').style.display='none';this.src='../../img/jia.jpg'}"><input type="radio" value="|256," onClick="window.parent.document.getElementById('ZiCLB_2').value='人力资源';window.parent.document.getElementById('ZiCLB').value='|256,';window.parent.document.getElementById('Cate').style.visibility='hidden';window.parent.document.getElementById('Postit').submit()" style="border: 0px; border-top: 6px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept">&nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="256o" name="|256,o">人力资源</a></font></font><div id="256256" style="padding-left: 20px; display: none">
			<img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('257257').style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('257257').style.display=''}else{document.getElementById('257257').style.display='none';this.src='../../img/jia.jpg'}"><input type="radio" value="|256,|257," onClick="window.parent.document.getElementById('ZiCLB_2').value='外部顾问';window.parent.document.getElementById('ZiCLB').value='|256,|257,';window.parent.document.getElementById('Cate').style.visibility='hidden';window.parent.document.getElementById('Postit').submit()" style="border: 0px; border-top: 6px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept">&nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="257o" name="|256,|257,o">外部顾问</a></font></font><br><div id="257257" style="padding-left: 20px; display: none"></div>
			
			<img src="../../img/jia.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('258258').style.display=='none'){this.src='../../img/jian.jpg';document.getElementById('258258').style.display=''}else{document.getElementById('258258').style.display='none';this.src='../../img/jia.jpg'}"><input type="radio" value="|256,|258," onClick="window.parent.document.getElementById('ZiCLB_2').value='内部研发人员';window.parent.document.getElementById('ZiCLB').value='|256,|258,';window.parent.document.getElementById('Cate').style.visibility='hidden';window.parent.document.getElementById('Postit').submit()" style="border: 0px; border-top: 6px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept">&nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand; color: black"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="258o" name="|256,|258,o">内部研发人员</a></font></font><br><div id="258258" style="padding-left: 20px; display: none"></div>
			</div></div>
		
	</td>
  </tr>
</table></div></td>
  </tr>
</table>
</div>
<script language="javascript">
if (window.top.location.href.indexOf("itsm.htm")>0){
	var Url = window.location.href;
	Url = Url.replace(/\&/g,"|@|");
	Url = Url.replace(/\#/g,"|$|");
	Url = Url.replace(/\?/g,"|~|");
	window.top.themain.mainit.topit.currurl.location.replace("../home/?NowAction=CurrURL&CurrURL="+Url);
}
</script>
</body>
</html>
