<%@ page language="java" contentType="text/html; charset=utf-8" isELIgnored="false"%>
<%@ taglib prefix="s" uri="/struts-tags"%>

<!--TestRecords:500//-->
<script language="javascript" event="onerror(msg, url, line)" for="window">return true;</script>

<html><head>
<link rel="stylesheet" type="text/css" href="../theme/admin.css">

<Script Language="JavaScript">
function CheckBox(obj,id)
{
	var value=obj.value;
	var parents=window.parent.document.getElementById('field2');
	if (parents.value.length<1700)
	{
		var allLine=document.body.all.item("dept");
		if (allLine!=null)
		{
			var count=allLine.length;
			if (count)
			{
				for (i=0; i<count; i++)
				{
					if (allLine[i].title.indexOf(value)>0)
					{
						if (id=="OK")
						{
							if (parents.value.length<1700)
							{
								allLine[i].checked=true;
								parents.value=parents.value.replace('<'+allLine[i].value+'>','')+'<'+allLine[i].value+'>';
							}
							else
							{
								alert('Sorry, Overflow!!');
								allLine[i].focus();
								break;
							}
						}
						else
						{
							allLine[i].checked=false;
							parents.value=parents.value.replace('<'+allLine[i].value+'>','');
						}
					}
				}
			}
		}
	}
	else
	{
		obj.checked=false;
		parents.value=parents.value.replace('<'+value+'>','');
		if (id=="OK")
		{
			alert("Sorry, overflow!");
		}
	}
}
function ClearAll()
{
	var allLine=document.body.all.item("dept");
	if (allLine!=null)
	{
		var count=allLine.length;
		if (count)
		{
			for (i=count-1; i>=0; i--)
			{
				allLine[i].checked=false;
			}
		}
	}
}
function OnUp()
{
	
}
</Script>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" style="padding-bottom: 2px; padding-top: 2px; overflow-x: hidden; overflow-y: scroll" onselectstart="return false">
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td style="line-height: 19px; font-family: Tahoma; padding-left: 2px; padding-bottom: 4px" bgColor="white" nowrap>
	
			<div><img src="../img/jian.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('228228').style.display=='none'){document.getElementById('228228').style.display='';this.src='../img/jian.jpg'}else{document.getElementById('228228').style.display='none';this.src='../img/jia.jpg'}"><input type="checkbox" value="|228," onClick="if(this.checked){window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|228,>','')+'<|228,>';CheckBox(this,'OK')}else{window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|228,>','');CheckBox(this,'NO')};OnUp()" style="border: 0px; border-top: 5px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept" title="Tree_|228,">&nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="228o" name="|228,o">员工离职IT信息管理变更</a></font></font><div id="228228" style="padding-left: 20px"></div></div>
		
			<div><img src="../img/jian.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('229229').style.display=='none'){document.getElementById('229229').style.display='';this.src='../img/jian.jpg'}else{document.getElementById('229229').style.display='none';this.src='../img/jia.jpg'}"><input type="checkbox" value="|229," onClick="if(this.checked){window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|229,>','')+'<|229,>';CheckBox(this,'OK')}else{window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|229,>','');CheckBox(this,'NO')};OnUp()" style="border: 0px; border-top: 5px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept" title="Tree_|229,">&nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="229o" name="|229,o">员工入职IT信息管理申请</a></font></font><div id="229229" style="padding-left: 20px"></div></div>
		
			<div><img src="../img/jian.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('230230').style.display=='none'){document.getElementById('230230').style.display='';this.src='../img/jian.jpg'}else{document.getElementById('230230').style.display='none';this.src='../img/jia.jpg'}"><input type="checkbox" value="|230," onClick="if(this.checked){window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|230,>','')+'<|230,>';CheckBox(this,'OK')}else{window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|230,>','');CheckBox(this,'NO')};OnUp()" style="border: 0px; border-top: 5px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept" title="Tree_|230,">&nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="230o" name="|230,o">员工调动IT信息管理变更</a></font></font><div id="230230" style="padding-left: 20px"></div></div>
		
			<div><img src="../img/jian.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('231231').style.display=='none'){document.getElementById('231231').style.display='';this.src='../img/jian.jpg'}else{document.getElementById('231231').style.display='none';this.src='../img/jia.jpg'}"><input type="checkbox" value="|231," onClick="if(this.checked){window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|231,>','')+'<|231,>';CheckBox(this,'OK')}else{window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|231,>','');CheckBox(this,'NO')};OnUp()" style="border: 0px; border-top: 5px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept" title="Tree_|231,">&nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="231o" name="|231,o">公司内网建设需求</a></font></font><div id="231231" style="padding-left: 20px"></div></div>
		
			<div><img src="../img/jian.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('243243').style.display=='none'){document.getElementById('243243').style.display='';this.src='../img/jian.jpg'}else{document.getElementById('243243').style.display='none';this.src='../img/jia.jpg'}"><input type="checkbox" value="|243," onClick="if(this.checked){window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,>','')+'<|243,>';CheckBox(this,'OK')}else{window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,>','');CheckBox(this,'NO')};OnUp()" style="border: 0px; border-top: 5px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept" title="Tree_|243,">&nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="243o" name="|243,o">硬件</a></font></font><div id="243243" style="padding-left: 20px">
			<img src="../img/jian.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('244244').style.display=='none'){this.src='../img/jian.jpg';document.getElementById('244244').style.display=''}else{document.getElementById('244244').style.display='none';this.src='../img/jia.jpg'}"><input type="checkbox" value="|243,|244," onClick="if(this.checked){window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,|244,>','')+'<|243,|244,>';CheckBox(this,'OK')}else{window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,|244,>','');CheckBox(this,'NO')};OnUp()" style="border: 0px; border-top: 5px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept" title="Tree_|243,|244,">&nbsp;<font style="padding: 1px"><font style="padding: 1px; cursor: hand; background-color: white"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="244o" name="|243,|244,o">服务器</a></font></font><br><div id="244244" style="padding-left: 20px">
			<img src="../img/jian.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('248248').style.display=='none'){this.src='../img/jian.jpg';document.getElementById('248248').style.display=''}else{document.getElementById('248248').style.display='none';this.src='../img/jia.jpg'}"><input type="checkbox" value="|243,|244,|248," onClick="if(this.checked){window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,|244,|248,>','')+'<|243,|244,|248,>';CheckBox(this,'OK')}else{window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,|244,|248,>','');CheckBox(this,'NO')};OnUp()" style="border: 0px; border-top: 5px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept" title="Tree_|243,|244,|248,">&nbsp;<font style="padding: 1px"><font style="padding: 1px; cursor: hand; background-color: white"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="248o" name="|243,|244,|248,o">品牌服务器</a></font></font><br><div id="248248" style="padding-left: 20px"></div>
			
			<img src="../img/jian.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('249249').style.display=='none'){this.src='../img/jian.jpg';document.getElementById('249249').style.display=''}else{document.getElementById('249249').style.display='none';this.src='../img/jia.jpg'}"><input type="checkbox" value="|243,|244,|249," onClick="if(this.checked){window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,|244,|249,>','')+'<|243,|244,|249,>';CheckBox(this,'OK')}else{window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,|244,|249,>','');CheckBox(this,'NO')};OnUp()" style="border: 0px; border-top: 5px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept" title="Tree_|243,|244,|249,">&nbsp;<font style="padding: 1px"><font style="padding: 1px; cursor: hand; background-color: white"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="249o" name="|243,|244,|249,o">普PC服务器</a></font></font><br><div id="249249" style="padding-left: 20px"></div>
			
			<img src="../img/jian.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('273273').style.display=='none'){this.src='../img/jian.jpg';document.getElementById('273273').style.display=''}else{document.getElementById('273273').style.display='none';this.src='../img/jia.jpg'}"><input type="checkbox" value="|243,|244,|273," onClick="if(this.checked){window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,|244,|273,>','')+'<|243,|244,|273,>';CheckBox(this,'OK')}else{window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,|244,|273,>','');CheckBox(this,'NO')};OnUp()" style="border: 0px; border-top: 5px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept" title="Tree_|243,|244,|273,">&nbsp;<font style="padding: 1px"><font style="padding: 1px; cursor: hand; background-color: white"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="273o" name="|243,|244,|273,o">服务器硬盘扩容</a></font></font><br><div id="273273" style="padding-left: 20px"></div>
			</div>
			
			<img src="../img/jian.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('245245').style.display=='none'){this.src='../img/jian.jpg';document.getElementById('245245').style.display=''}else{document.getElementById('245245').style.display='none';this.src='../img/jia.jpg'}"><input type="checkbox" value="|243,|245," onClick="if(this.checked){window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,|245,>','')+'<|243,|245,>';CheckBox(this,'OK')}else{window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,|245,>','');CheckBox(this,'NO')};OnUp()" style="border: 0px; border-top: 5px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept" title="Tree_|243,|245,">&nbsp;<font style="padding: 1px"><font style="padding: 1px; cursor: hand; background-color: white"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="245o" name="|243,|245,o">桌面机</a></font></font><br><div id="245245" style="padding-left: 20px">
			<img src="../img/jian.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('250250').style.display=='none'){this.src='../img/jian.jpg';document.getElementById('250250').style.display=''}else{document.getElementById('250250').style.display='none';this.src='../img/jia.jpg'}"><input type="checkbox" value="|243,|245,|250," onClick="if(this.checked){window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,|245,|250,>','')+'<|243,|245,|250,>';CheckBox(this,'OK')}else{window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,|245,|250,>','');CheckBox(this,'NO')};OnUp()" style="border: 0px; border-top: 5px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept" title="Tree_|243,|245,|250,">&nbsp;<font style="padding: 1px"><font style="padding: 1px; cursor: hand; background-color: white"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="250o" name="|243,|245,|250,o">台式机</a></font></font><br><div id="250250" style="padding-left: 20px"></div>
			
			<img src="../img/jian.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('251251').style.display=='none'){this.src='../img/jian.jpg';document.getElementById('251251').style.display=''}else{document.getElementById('251251').style.display='none';this.src='../img/jia.jpg'}"><input type="checkbox" value="|243,|245,|251," onClick="if(this.checked){window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,|245,|251,>','')+'<|243,|245,|251,>';CheckBox(this,'OK')}else{window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,|245,|251,>','');CheckBox(this,'NO')};OnUp()" style="border: 0px; border-top: 5px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept" title="Tree_|243,|245,|251,">&nbsp;<font style="padding: 1px"><font style="padding: 1px; cursor: hand; background-color: white"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="251o" name="|243,|245,|251,o">笔记本</a></font></font><br><div id="251251" style="padding-left: 20px"></div>
			</div>
			
			<img src="../img/jian.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('246246').style.display=='none'){this.src='../img/jian.jpg';document.getElementById('246246').style.display=''}else{document.getElementById('246246').style.display='none';this.src='../img/jia.jpg'}"><input type="checkbox" value="|243,|246," onClick="if(this.checked){window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,|246,>','')+'<|243,|246,>';CheckBox(this,'OK')}else{window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,|246,>','');CheckBox(this,'NO')};OnUp()" style="border: 0px; border-top: 5px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept" title="Tree_|243,|246,">&nbsp;<font style="padding: 1px"><font style="padding: 1px; cursor: hand; background-color: white"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="246o" name="|243,|246,o">网络设备</a></font></font><br><div id="246246" style="padding-left: 20px">
			<img src="../img/jian.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('252252').style.display=='none'){this.src='../img/jian.jpg';document.getElementById('252252').style.display=''}else{document.getElementById('252252').style.display='none';this.src='../img/jia.jpg'}"><input type="checkbox" value="|243,|246,|252," onClick="if(this.checked){window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,|246,|252,>','')+'<|243,|246,|252,>';CheckBox(this,'OK')}else{window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,|246,|252,>','');CheckBox(this,'NO')};OnUp()" style="border: 0px; border-top: 5px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept" title="Tree_|243,|246,|252,">&nbsp;<font style="padding: 1px"><font style="padding: 1px; cursor: hand; background-color: white"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="252o" name="|243,|246,|252,o">路由器</a></font></font><br><div id="252252" style="padding-left: 20px"></div>
			
			<img src="../img/jian.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('253253').style.display=='none'){this.src='../img/jian.jpg';document.getElementById('253253').style.display=''}else{document.getElementById('253253').style.display='none';this.src='../img/jia.jpg'}"><input type="checkbox" value="|243,|246,|253," onClick="if(this.checked){window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,|246,|253,>','')+'<|243,|246,|253,>';CheckBox(this,'OK')}else{window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,|246,|253,>','');CheckBox(this,'NO')};OnUp()" style="border: 0px; border-top: 5px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept" title="Tree_|243,|246,|253,">&nbsp;<font style="padding: 1px"><font style="padding: 1px; cursor: hand; background-color: white"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="253o" name="|243,|246,|253,o">交换机</a></font></font><br><div id="253253" style="padding-left: 20px"></div>
			
			<img src="../img/jian.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('254254').style.display=='none'){this.src='../img/jian.jpg';document.getElementById('254254').style.display=''}else{document.getElementById('254254').style.display='none';this.src='../img/jia.jpg'}"><input type="checkbox" value="|243,|246,|254," onClick="if(this.checked){window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,|246,|254,>','')+'<|243,|246,|254,>';CheckBox(this,'OK')}else{window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,|246,|254,>','');CheckBox(this,'NO')};OnUp()" style="border: 0px; border-top: 5px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept" title="Tree_|243,|246,|254,">&nbsp;<font style="padding: 1px"><font style="padding: 1px; cursor: hand; background-color: white"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="254o" name="|243,|246,|254,o">防火墙</a></font></font><br><div id="254254" style="padding-left: 20px"></div>
			</div>
			
			<img src="../img/jian.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('247247').style.display=='none'){this.src='../img/jian.jpg';document.getElementById('247247').style.display=''}else{document.getElementById('247247').style.display='none';this.src='../img/jia.jpg'}"><input type="checkbox" value="|243,|247," onClick="if(this.checked){window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,|247,>','')+'<|243,|247,>';CheckBox(this,'OK')}else{window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,|247,>','');CheckBox(this,'NO')};OnUp()" style="border: 0px; border-top: 5px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept" title="Tree_|243,|247,">&nbsp;<font style="padding: 1px"><font style="padding: 1px; cursor: hand; background-color: white"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="247o" name="|243,|247,o">外围设备</a></font></font><br><div id="247247" style="padding-left: 20px">
			<img src="../img/jian.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('255255').style.display=='none'){this.src='../img/jian.jpg';document.getElementById('255255').style.display=''}else{document.getElementById('255255').style.display='none';this.src='../img/jia.jpg'}"><input type="checkbox" value="|243,|247,|255," onClick="if(this.checked){window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,|247,|255,>','')+'<|243,|247,|255,>';CheckBox(this,'OK')}else{window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,|247,|255,>','');CheckBox(this,'NO')};OnUp()" style="border: 0px; border-top: 5px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept" title="Tree_|243,|247,|255,">&nbsp;<font style="padding: 1px"><font style="padding: 1px; cursor: hand; background-color: white"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="255o" name="|243,|247,|255,o">扫描仪</a></font></font><br><div id="255255" style="padding-left: 20px"></div>
			
			<img src="../img/jian.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('256256').style.display=='none'){this.src='../img/jian.jpg';document.getElementById('256256').style.display=''}else{document.getElementById('256256').style.display='none';this.src='../img/jia.jpg'}"><input type="checkbox" value="|243,|247,|256," onClick="if(this.checked){window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,|247,|256,>','')+'<|243,|247,|256,>';CheckBox(this,'OK')}else{window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,|247,|256,>','');CheckBox(this,'NO')};OnUp()" style="border: 0px; border-top: 5px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept" title="Tree_|243,|247,|256,">&nbsp;<font style="padding: 1px"><font style="padding: 1px; cursor: hand; background-color: white"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="256o" name="|243,|247,|256,o">打印机</a></font></font><br><div id="256256" style="padding-left: 20px"></div>
			
			<img src="../img/jian.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('257257').style.display=='none'){this.src='../img/jian.jpg';document.getElementById('257257').style.display=''}else{document.getElementById('257257').style.display='none';this.src='../img/jia.jpg'}"><input type="checkbox" value="|243,|247,|257," onClick="if(this.checked){window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,|247,|257,>','')+'<|243,|247,|257,>';CheckBox(this,'OK')}else{window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,|247,|257,>','');CheckBox(this,'NO')};OnUp()" style="border: 0px; border-top: 5px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept" title="Tree_|243,|247,|257,">&nbsp;<font style="padding: 1px"><font style="padding: 1px; cursor: hand; background-color: white"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="257o" name="|243,|247,|257,o">复印机</a></font></font><br><div id="257257" style="padding-left: 20px"></div>
			
			<img src="../img/jian.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('258258').style.display=='none'){this.src='../img/jian.jpg';document.getElementById('258258').style.display=''}else{document.getElementById('258258').style.display='none';this.src='../img/jia.jpg'}"><input type="checkbox" value="|243,|247,|258," onClick="if(this.checked){window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,|247,|258,>','')+'<|243,|247,|258,>';CheckBox(this,'OK')}else{window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,|247,|258,>','');CheckBox(this,'NO')};OnUp()" style="border: 0px; border-top: 5px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept" title="Tree_|243,|247,|258,">&nbsp;<font style="padding: 1px"><font style="padding: 1px; cursor: hand; background-color: white"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="258o" name="|243,|247,|258,o">一体机</a></font></font><br><div id="258258" style="padding-left: 20px"></div>
			
			<img src="../img/jian.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('259259').style.display=='none'){this.src='../img/jian.jpg';document.getElementById('259259').style.display=''}else{document.getElementById('259259').style.display='none';this.src='../img/jia.jpg'}"><input type="checkbox" value="|243,|247,|259," onClick="if(this.checked){window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,|247,|259,>','')+'<|243,|247,|259,>';CheckBox(this,'OK')}else{window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|243,|247,|259,>','');CheckBox(this,'NO')};OnUp()" style="border: 0px; border-top: 5px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept" title="Tree_|243,|247,|259,">&nbsp;<font style="padding: 1px"><font style="padding: 1px; cursor: hand; background-color: white"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="259o" name="|243,|247,|259,o">显示器</a></font></font><br><div id="259259" style="padding-left: 20px"></div>
			</div>
			</div></div>
		
			<div><img src="../img/jian.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('279279').style.display=='none'){document.getElementById('279279').style.display='';this.src='../img/jian.jpg'}else{document.getElementById('279279').style.display='none';this.src='../img/jia.jpg'}"><input type="checkbox" value="|279," onClick="if(this.checked){window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|279,>','')+'<|279,>';CheckBox(this,'OK')}else{window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|279,>','');CheckBox(this,'NO')};OnUp()" style="border: 0px; border-top: 5px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept" title="Tree_|279,">&nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="279o" name="|279,o">项目审批</a></font></font><div id="279279" style="padding-left: 20px">
			<img src="../img/jian.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('280280').style.display=='none'){this.src='../img/jian.jpg';document.getElementById('280280').style.display=''}else{document.getElementById('280280').style.display='none';this.src='../img/jia.jpg'}"><input type="checkbox" value="|279,|280," onClick="if(this.checked){window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|279,|280,>','')+'<|279,|280,>';CheckBox(this,'OK')}else{window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|279,|280,>','');CheckBox(this,'NO')};OnUp()" style="border: 0px; border-top: 5px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept" title="Tree_|279,|280,">&nbsp;<font style="padding: 1px"><font style="padding: 1px; cursor: hand; background-color: white"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="280o" name="|279,|280,o">立项审批</a></font></font><br><div id="280280" style="padding-left: 20px"></div>
			
			<img src="../img/jian.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('281281').style.display=='none'){this.src='../img/jian.jpg';document.getElementById('281281').style.display=''}else{document.getElementById('281281').style.display='none';this.src='../img/jia.jpg'}"><input type="checkbox" value="|279,|281," onClick="if(this.checked){window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|279,|281,>','')+'<|279,|281,>';CheckBox(this,'OK')}else{window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|279,|281,>','');CheckBox(this,'NO')};OnUp()" style="border: 0px; border-top: 5px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept" title="Tree_|279,|281,">&nbsp;<font style="padding: 1px"><font style="padding: 1px; cursor: hand; background-color: white"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="281o" name="|279,|281,o">项目阶段性评审</a></font></font><br><div id="281281" style="padding-left: 20px"></div>
			
			<img src="../img/jian.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('282282').style.display=='none'){this.src='../img/jian.jpg';document.getElementById('282282').style.display=''}else{document.getElementById('282282').style.display='none';this.src='../img/jia.jpg'}"><input type="checkbox" value="|279,|282," onClick="if(this.checked){window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|279,|282,>','')+'<|279,|282,>';CheckBox(this,'OK')}else{window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|279,|282,>','');CheckBox(this,'NO')};OnUp()" style="border: 0px; border-top: 5px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept" title="Tree_|279,|282,">&nbsp;<font style="padding: 1px"><font style="padding: 1px; cursor: hand; background-color: white"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="282o" name="|279,|282,o">结项审批</a></font></font><br><div id="282282" style="padding-left: 20px"></div>
			</div></div>
		
			<div><img src="../img/jian.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white" onClick="if(document.getElementById('283283').style.display=='none'){document.getElementById('283283').style.display='';this.src='../img/jian.jpg'}else{document.getElementById('283283').style.display='none';this.src='../img/jia.jpg'}"><input type="checkbox" value="|283," onClick="if(this.checked){window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|283,>','')+'<|283,>';CheckBox(this,'OK')}else{window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|283,>','');CheckBox(this,'NO')};OnUp()" style="border: 0px; border-top: 5px solid white; width: 19px; border-left: 4px solid white"  id="dept" name="dept" title="Tree_|283,">&nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="283o" name="|283,o">程序变更及发布</a></font></font><div id="283283" style="padding-left: 20px"></div></div>
		
	<div><img src="../img/point.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white"><input type="checkbox" value="All3" onClick="if(this.checked){window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<All3>','')+'<All3>'}else{window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<All3>','')}" style="border: 0px; border-top: 5px solid white; border-left: 4px solid white; width: 19px"  id="dept" name="dept">&nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="All" name="All">所有类别</a></font></font></div>
	
	<div><img src="../img/point.jpg" width="11" height="11" align="absmiddle" style="border: 4px solid white; border-top: 7px solid white"><input type="checkbox" onClick="window.parent.document.getElementById('field2').value='';ClearAll()" style="border: 0px; border-top: 5px solid white; width: 19px; border-left: 4px solid white">&nbsp;<font style="padding: 1px"><font style="padding: 1px; background-color: white; cursor: hand"><a onMouseOver="this.style.borderBottom='1px solid'" onMouseOut="this.style.borderBottom='0px solid'" id="Mail" name="Mail">清空所有选择</a></font></font></div>
	
		</td>
	</tr>
	<tr>
		
		<td style="border: 1px outset; padding-left: 5px" bgcolor="#E1DFD9">
		
		<table width="20" border="0" cellspacing="0" cellpadding="0">
		  <tr>
			<td style="padding-right: 6px; padding-bottom: 1px"><img src="../img/point.jpg" width="11" height="11" align="absmiddle"></td>
			<td style="padding-bottom: 1px"><input type="checkbox" value="|A|" onClick="if(this.checked){window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|A|>','')+'<|A|>'}else{window.parent.document.getElementById('field2').value=window.parent.document.getElementById('field2').value.replace('<|A|>','')}" style="width: 19px; border: 0px"  id="dept" name="dept"></td>
			<td nowrap><b>&nbsp;优先级: 全部</b></td>
		  </tr>
		</table>
		</td>
	</tr>
	<tr>
		<td style="line-height: 19px; font-family: Tahoma; padding-left: 7px; padding-bottom: 2px" bgColor="white" nowrap>
		<table width="70%" border="0" cellspacing="2" cellpadding="0">
		
		</table>
		
	</td>
  </tr>
</table>